# Generated by Django 5.2.8 on 2025-11-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('total_score', models.FloatField(default=100.0)),
                ('topic', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('short_answer', 'Short Answer'), ('multiple_choice', 'Multiple Choice'), ('file_upload', 'File Upload')], max_length=20)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('score', models.FloatField(default=1.0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
        ),
    ]
